---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: database
spec:
  provider: aws
  secretObjects:
  - secretName: mongodb
    type: Opaque
    data: 
      - objectName: newwm-1
        key: mongodb-password
      - objectName: newwm-2
        key: mongodb-root-password
      - objectName: newwm
        key: mongodb-replica-set-key
  parameters:
    objects: |
        - objectName: database/replica1
          objectType: secretsmanager
          objectAlias: newwm
        - objectName: database/pw
          objectType: secretsmanager
          objectAlias: newwm-1
        - objectName: database/rootpw
          objectType: secretsmanager
          objectAlias: newwm-2
